// conti/src/main/webapp/app/entities/conti/conto/detail/conto-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IConto } from '../conto.model';

@Component({
  selector: 'jhi-conto-detail',
  templateUrl: './conto-detail.component.html',
})
export class ContoDetailComponent implements OnInit {
  conto: IConto | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ conto }) => {
      this.conto = conto;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="conto">
      <h2 data-cy="contoDetailsHeading"><span jhiTranslate="contiApp.contiConto.detail.title">Conto</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ conto.id }}</span>
        </dd>
        <dt><span jhiTranslate="contiApp.contiConto.nome">Nome</span></dt>
        <dd>
          <span>{{ conto.nome }}</span>
        </dd>
        <dt><span jhiTranslate="contiApp.contiConto.iban">Iban</span></dt>
        <dd>
          <span>{{ conto.iban }}</span>
        </dd>
        <dt><span jhiTranslate="contiApp.contiConto.userName">User Name</span></dt>
        <dd>
          <span>{{ conto.userName }}</span>
        </dd>
        <dt><span jhiTranslate="contiApp.contiConto.abi">Abi</span></dt>
        <dd>
          <span>{{ conto.abi }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/conti/conto', conto.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// gateway/src/main/webapp/app/entities/conti/conto/conto-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './conto.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ContoDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const contoEntity = useAppSelector(state => state.conto.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="contoDetailsHeading">
          <Translate contentKey="gatewayApp.contiConto.detail.title">Conto</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{contoEntity.id}</dd>
          <dt>
            <span id="nome">
              <Translate contentKey="gatewayApp.contiConto.nome">Nome</Translate>
            </span>
          </dt>
          <dd>{contoEntity.nome}</dd>
          <dt>
            <span id="iban">
              <Translate contentKey="gatewayApp.contiConto.iban">Iban</Translate>
            </span>
          </dt>
          <dd>{contoEntity.iban}</dd>
          <dt>
            <span id="userName">
              <Translate contentKey="gatewayApp.contiConto.userName">User Name</Translate>
            </span>
          </dt>
          <dd>{contoEntity.userName}</dd>
          <dt>
            <span id="abi">
              <Translate contentKey="gatewayApp.contiConto.abi">Abi</Translate>
            </span>
          </dt>
          <dd>{contoEntity.abi}</dd>
        </dl>
        <Button tag={Link} to="/conto" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/conto/${contoEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ContoDetail;
