// gateway/src/main/webapp/app/entities/conti/conto/conto-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './conto.reducer';

export const ContoDeleteDialog = (props: RouteComponentProps<{ id: string }>) => {
  const [loadModal, setLoadModal] = useState(false);
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
    setLoadModal(true);
  }, []);

  const contoEntity = useAppSelector(state => state.conto.entity);
  const updateSuccess = useAppSelector(state => state.conto.updateSuccess);

  const handleClose = () => {
    props.history.push('/conto');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(contoEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="contoDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="gatewayApp.contiConto.delete.question">
        <Translate contentKey="gatewayApp.contiConto.delete.question" interpolate={{ id: contoEntity.id }}>
          Are you sure you want to delete this Conto?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-conto" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default ContoDeleteDialog;

// conti/src/main/webapp/app/entities/conti/conto/delete/conto-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { IConto } from '../conto.model';
import { ContoService } from '../service/conto.service';

@Component({
  templateUrl: './conto-delete-dialog.component.html',
})
export class ContoDeleteDialogComponent {
  conto?: IConto;

  constructor(protected contoService: ContoService, protected activeModal: NgbActiveModal) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.contoService.delete(id).subscribe(() => {
      this.activeModal.close('deleted');
    });
  }
}

<form *ngIf="conto" name="deleteForm" (ngSubmit)="confirmDelete(conto.id!)">
  <div class="modal-header">
    <h4 class="modal-title" data-cy="contoDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()">&times;</button>
  </div>

  <div class="modal-body">
    <jhi-alert-error></jhi-alert-error>

    <p id="jhi-delete-conto-heading" jhiTranslate="contiApp.contiConto.delete.question" [translateValues]="{ id: conto.id }">
      Are you sure you want to delete this Conto?
    </p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
      <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
    </button>

    <button id="jhi-confirm-delete-conto" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
      <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
    </button>
  </div>
</form>
